### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: no such file or directory

### ISSUE THREAD

**Issue by wakingrufus** [beryx/badass-runtime-plugin#125]
I am using the `image/` output from the `runtime` task to build a docker image.
I am using `gcr.io/distroless/base` and building with jib.
when i run the docker image, it fails with ```standard_init_linux.go:228: exec user process caused: no such file or directory```
from some googling, this seems to be related to line endings. I verified that the start script generated by `runtime` has linux line endings (i am building on linux). 
Does anyone else have this issue and know a solution?

**Comment by hakanai** [comment]
This seems unrelated. You're not going to get a "no such file or directory" error due to line endings of the file. Just think about the order of operations things would have to happen in.

I'm going to pin this on sthe other tool. Perhaps it's assuming a particular layout that isn't the case. Or perhaps it isn't the tool, but rather something in the `Dockerfile`, or some other program being launched from docker.

If you do find that somehow the wrong line endings were coming out of this plugin, however, open a ticket with that as the precise issue.
