### ISSUE TITLE
Platform binaries does not use the right jvm binaries

### ISSUE THREAD

**Issue by nsteinmetz** [beryx/badass-runtime-plugin#35]
Hello,

Noticed using 1.2.0 and confirmed with 1.6.0:
* If we build the project on osx, the java binary included in the linux/osx/windows package is the osx one
*If we build the project on linux, the java binary included in the linux/osx/windows package is the linux one

So we can't distribute our app built on our jenkins server except for linux boxes.

Our current setup:

```
        val runtimeBeryx = the<RuntimePluginExtension>()
        runtimeBeryx.addOptions("--strip-debug", "--compress", "2", "--no-header-files", "--no-man-pages")
        runtimeBeryx.targetPlatform("linux-x64", "../.gradle/jdk/linux/jdk-11.0.3+7")
        runtimeBeryx.targetPlatform("osx-x64", "../.gradle/jdk/mac/jdk-11.0.3+7/Contents/Home")
        runtimeBeryx.targetPlatform("windows-x64", "../.gradle/jdk/windows/jdk-11.0.3+7")
```

I went through the issues but I did not find anything close to my case.

My guess is that it only uses the default java version of the platform but can't find where I could change anything on this.

Thanks !

**Comment by siordache** [comment]
I cannot reproduce this problem. I updated [badass-runtime-example-kotlin-tornadofx](https://github.com/beryx-gist/badass-runtime-example-kotlin-tornadofx) to create custom runtime images for [multiple platforms](https://github.com/beryx-gist/badass-runtime-example-kotlin-tornadofx/blob/9694837aefb412bcc95760a39e1b7072fa42441d/build.gradle.kts#L58-L60) and the java binaries are in accordance with the target platform.
I configured Travis to push the generated custom runtime images to the ['images' branch](https://github.com/beryx-gist/badass-runtime-example-kotlin-tornadofx/tree/images) so you can have a look at them.

However, I had problems with the javafx libraries, because the [javafxplugin](https://github.com/openjfx/javafx-gradle-plugin) includes the binaries for the platform running the build. Currently, the badass-runtime-plugin lacks support for this use case, so I needed to adjust the build script in a couple of places (such as [here](https://github.com/beryx-gist/badass-runtime-example-kotlin-tornadofx/blob/9694837aefb412bcc95760a39e1b7072fa42441d/build.gradle.kts#L44-L50) and [here](https://github.com/beryx-gist/badass-runtime-example-kotlin-tornadofx/blob/9694837aefb412bcc95760a39e1b7072fa42441d/build.gradle.kts#L69-L79)) to make it generate valid custom runtime images for all platforms.


Maybe comparing your build.gradle.kts with the one in [badass-runtime-example-kotlin-tornadofx](https://github.com/beryx-gist/badass-runtime-example-kotlin-tornadofx) will help you solve your problem.

Here the environment variables I configured for Travis:
```
JDK_LINUX_URL = https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.4%2B11/OpenJDK11U-jdk_x64_linux_hotspot_11.0.4_11.tar.gz
JDK_LINUX_HOME = linux/jdk-11.0.4+11

JDK_MAC_URL = https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.4%2B11.4/OpenJDK11U-jdk_x64_mac_hotspot_11.0.4_11.tar.gz
JDK_MAC_HOME = mac/jdk-11.0.4+11/Contents/Home

JDK_WIN_URL = https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.4%2B11/OpenJDK11U-jdk_x64_windows_hotspot_11.0.4_11.zip
JDK_WIN_HOME = win/jdk-11.0.4+11
```

If you still cannot find a solution, please try to create a [SSCCE](http://sscce.org/) that allows me to reproduce the issue.

**Comment by nsteinmetz** [comment]
Hi,

Thanks for your feedback and your time.

Taking the problem from zero, I finally found the issue, our gradle task to download and unzip jdk did not work well. So if JDK is not extracted, then JDK is not found by the plugin and so it uses the default jdk available on the system to build all the binaries.

Sorry for wasting your time - maybe a warning informing that defined jdk is not available and defaulting to system's one could be worth to be added.

Have a nice day,
Nicolas

**Comment by siordache** [comment]
@nsteinmetz  Defaulting to the system's jdk is confusing and does more harm than good. In release 1.6.1 the plugin exits with an error if a jdk home has been configured but it's not available.

**Comment by nsteinmetz** [comment]
Awesome, thanks !
