### ISSUE TITLE
Windows: launcher jvmArgs containing %VAR% escaped incorrectly

### ISSUE THREAD

**Issue by llongi** [beryx/badass-runtime-plugin#69]
When using the launcher's 'jvmArgs' option to pass a list of JVM arguments, we're seeing different behavior than the badass-jlink-plugin.

Take for example the following JVM argument that contains a Windows %VAR%:

`jvmArgs = ["-Djavafx.cachedir=%PROGRAMDATA%\\openjfx\\$javafx.version"]`

this resolves to the following in the generated batch file:

`set DEFAULT_JVM_OPTS="-Djavafx.cachedir=%%PROGRAMDATA%%\openjfx\14.0.2.1"`

See the double %%? That completely breaks it. In the jlink plugin the resulting substitution is correctly:

`"-Djavafx.cachedir=%PROGRAMDATA%\openjfx\14.0.2.1"`

It looks like something is different about how the templates are filled out or their values escaped.
Thank you for your help!

**Comment by siordache** [comment]
The badass-jlink-plugin renders itself the templates. In the badass-runtime-plugin, the templates are rendered by the [createStartScripts](https://docs.gradle.org/current/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.html) task, which [escapes the % sign](https://github.com/gradle/gradle/blob/923563e47ce8d69ac44a8d89ea16125b93caadab/subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/StartScriptTemplateBindingFactory.java#L145-L146). That's why the subsitution doesn't work with this plugin.

In badass-runtime-plugin 1.11.4 and in badass-jlink-plugin 2.21.4 you can pass environment variables to jvmArgs by enclosing them between `{{` and `}}`:
```
jvmArgs = ["-Djavafx.cachedir={{PROGRAMDATA}}\\openjfx\\$javafx.version"]
```

The plugins will expand them using the platform-specific syntax (e.g., %PROGRAMDATA% on Windows and $PROGRAMDATA on Linux and macOS).

**Comment by llongi** [comment]
Thank you for the great support!
Tested the new syntax on both runtime 1.11.4 and jlink 2.21.4, works fine on Windows for both.
Issue can be closed from my side.

**Comment by siordache** [comment]
Thanks for the feedback!
