### ISSUE TITLE
Jar specification missing from the bat file

### ISSUE THREAD

**Issue by diniamo** [beryx/badass-runtime-plugin#80]
So, I have a TornadoFX application, and I got the plugin up and working, had to do a little debugging, and I found the problem, it's that the execute part doesn't specify the jar itself.

This is the line: `%JAVA_EXE% %DEFAULT_JVM_OPTS% %JAVA_OPTS% %SM_PIXEL_ART_CREATOR_OPTS%  -classpath %CLASSPATH%  %CMD_LINE_ARGS%`

I have to manually edit it on every build to something like this: `%JAVA_EXE% -jar ../lib/MyApp-1.0-SNAPSHOT.jar %DEFAULT_JVM_OPTS% %JAVA_OPTS% %SM_PIXEL_ART_CREATOR_OPTS%  -classpath %CLASSPATH%  %CMD_LINE_ARGS%`

**Comment by diniamo** [comment]
Seems like I was on a really old version (the latest version should be specified on top of README), but updating didn't fix anything.

**Comment by siordache** [comment]
Yes, the jar specification is missing from the bat file. That's by design. The plugin generates a start script that works by specifying the classpath, not a jar file. In a simplified form, the resulting start command looks like this:
```
java -classpath ../lib/* <main-class>
```

Check if you correctly configured the main class using the [Application plugin](https://docs.gradle.org/current/userguide/application_plugin.html#sec:application_usage):
```
application {
    mainClass = 'sm.pixel.art.creator.Main'
}
```

**Comment by diniamo** [comment]
That seems to have one it.

Thought it would be enough to just do it this way: 
```
tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "me.diniamo.pixelartcreator.MyAppKt"
    }
